name: Release with Version

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Install dependencies
        run: flutter pub get

      - name: Get version
        id: get_version
        run: echo "::set-output name=version::$(grep 'version:' pubspec.yaml | head -1 | awk '{ print $2 }' | tr -d "'")"

      - name: Build APK
        run: flutter build apk --release

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./build/app/outputs/flutter-apk/app-release.apk
          tag_name: ${{ steps.get_version.outputs.version }}
          body: |
            ### Version: ${{ steps.get_version.outputs.version }}
            Automated APK release